
version: '3.8'

services:
  ksa-web:
    build: .
    container_name: admin_new
    command: npm run dev
    ports:
      - "3003:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true